#title: Lorenzo Fernández
logo: /assets/img/fotoSinFondo.png
description: ¡Hola! Soy Leonardo Lombana Contento. Bienvenido a mi portafolio de proyectos como QA Engineer.
show_downloads: false
theme: jekyll-theme-minimal
include: [styles.css]
